# This workflow will install Python dependencies, run tests with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Continuous testing

on:
  push:
    branches:
      - 'master'

  pull_request:
    branches:
      - 'master'

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_suite: ['data', 'models', 'training_scripts/denoising', 'training_scripts/multi_coil', 'training_scripts/dealiasing_train_test.py', 'training_scripts/ncpdnet_train_test.py', 'training_scripts/unet_nc_train_test.py', 'training_scripts/updnet_train_test.py', 'training_scripts/xpdnet_train_test.py']
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyxb
        pip install pytest==5.0.0 ismrmrd
        pip install .
        pip install -U --no-deps tensorflow-io==0.13.0
    - name: Test with pytest
      run: pytest -s fastmri_recon/tests/${{matrix.test_suite}}
